# -*- coding: utf-8 -*-
"""WQD7006_Lab3_P2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSngmYiJDDVk3YqDsYt8SusKCJF9ab4P

# Lab 3: Naive Bayes

## Part 1: Dataset Preparation
"""

# Preparing dummy dataset
import pandas as pd

data = {
    "StudyHours": ["High", "High", "Low", "Low", "High"],
    "Attendance": ["Good", "Poor", "Good", "Poor", "Good"],
    "Result": ["Pass", "Pass", "Fail", "Fail", "Pass"]
}

df = pd.DataFrame(data)
df

# What if one extra column is introduced?
df["SleepQuality"] = ["Good", "Poor", "Good", "Poor", "Good"]
df

"""## Part 2: Manual Probability Calculation

Prior Probabilities:
$$P(\text{Pass}) = \frac{3}{5} = 0.6$$
$$P(\text{Fail}) = \frac{2}{5} = 0.4$$

Likelihood Examples:
$$P(\text{High | Pass}) = \frac{3}{3} = 1.0$$
$$P(\text{Good | Pass}) = \frac{2}{3} ≈ 0.67$$

Posterior (unnormalized):
$$P(\text{Pass | High, Good}) ∝ 0.6 × 1.0 × 0.67 = 0.402$$
$$P(\text{Fail | High, Good}) ∝ 0.4 × 0 × 0.5 = 0$$

Prediction: PASS

## Part 3: Encoding Features
"""

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoded_df = df.copy()

for col in encoded_df.columns:
    encoded_df[col] = encoder.fit_transform(encoded_df[col])

encoded_df

"""## Part 4: Bernoulli Naive Bayes"""

# Why Bernoulli Naive Bayes is used?
from sklearn.naive_bayes import BernoulliNB

X = encoded_df[["StudyHours","Attendance"]]
y = encoded_df["Result"]

model = BernoulliNB()
model.fit(X, y)

"""## Part 5: Prediction"""

model.predict([[1,1]]), model.predict_proba([[1,1]])

# What is the difference?
new_student = pd.DataFrame(
    [[1, 1]],
    columns=["StudyHours", "Attendance"]
)
model.predict(new_student), model.predict_proba(new_student)

test_students = pd.DataFrame(
    [[1, 0],
     [0, 1],
     [0, 0]],
    columns=["StudyHours", "Attendance"]
)

model.predict(test_students), model.predict_proba(test_students)

"""## Part 6: Reflection

What are the advantages and disadvanges of Naive Bayes compared to other classifiers?
"""

# When should we use Gaussian Naive Bayes?
from sklearn.naive_bayes import GaussianNB

df_num = encoded_df.copy()
df_num["StudyHours"] = [6,7,3,2,8]

Xn = df_num[["StudyHours","Attendance"]]
yn = df_num["Result"]

g = GaussianNB()
g.fit(Xn, yn)

test = pd.DataFrame(
    [[5, 1],
     [1, 0],
     [0, 1],
     [0, 0]],
    columns=["StudyHours", "Attendance"]
)
g.predict(test), g.predict_proba(test)