# -*- coding: utf-8 -*-
"""WQD7006_Lab3_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkmff_v9CdeTGIhRFRG_d1pWMmvxjXVP

# Lab 3: KNN

## Part 0: Setup
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

"""## Part 1: Conceptual Understanding
**Question:** What is the role of K in KNN?

## Part 2: Load Dataset
"""

# Loading dataset that is available within scikit-learn package
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.Series(iris.target)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

X.head()

"""## Part 3: KNN Without Scaling"""

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

"""## Part 4: Feature Scaling"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)

y_pred_scaled = knn_scaled.predict(X_test_scaled)
accuracy_score(y_test, y_pred_scaled)

"""## Part 5: Distance Metrics"""

knn_manhattan = KNeighborsClassifier(n_neighbors=5, p=1)
knn_manhattan.fit(X_train_scaled, y_train)

y_pred_manhattan = knn_manhattan.predict(X_test_scaled)
accuracy_score(y_test, y_pred_manhattan)

"""Can you tell the difference between results with/without scaling, and results with Euclidean/Manhattan distance?

### Finding Optimal K
"""

k_values = range(1, 21)
accuracies = []

for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracies.append(accuracy_score(y_test, y_pred))

plt.plot(k_values, accuracies)
plt.xlabel("K")
plt.ylabel("Accuracy")
plt.show()

"""## Hyperparameter Tuning with GridSearch"""

# what are these parameters?
param_grid = {
    'n_neighbors': range(1, 21),
    'p': [1, 2],
    'weights': ['uniform', 'distance']
}

grid = GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=5,
    scoring='accuracy'
)

grid.fit(X_train_scaled, y_train)
grid.best_params_

"""## Model Evaluation using tuned parameters"""

best_knn = grid.best_estimator_
y_pred_pg = best_knn.predict(X_test_scaled)

print(confusion_matrix(y_test, y_pred_pg))
print(classification_report(y_test, y_pred_pg))

"""## Reflection

---


1. Discuss computational complexity of KNN.
2. Why is KNN unsuitable for very large datasets?
"""