# -*- coding: utf-8 -*-
"""WQD7006_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wNj_KabxrEbDLdnPQeKZAjx7q1yF2IBE

# WQD7006 Lab 1

This lab introduces basic Machine Learning concepts: task types, classification, regression, and supervised vs unsupervised learning.

## Part 1: Setup & Concept Mapping
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error

"""**Discussion:**
- Identify Task ($T$), Experience ($E$), and Performance ($P$) for weather prediction.
- Identify Task ($T$), Experience ($E$), and Performance ($P$) for stock lawsuit prediction.

## Part 2: Classification – Weather Prediction
"""

data = {
    'humidity': [30, 70, 90, 40, 80, 85],
    'temperature': [32, 28, 25, 34, 26, 24],
    'weather': ['Sunny', 'Cloudy', 'Rainy', 'Sunny', 'Rainy', 'Rainy']
}

df = pd.DataFrame(data)
df

# labelEncoder or one hot encoder?
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['weather_encoded'] = le.fit_transform(df['weather'])
df

# Simple example using decision tree
from sklearn.tree import DecisionTreeClassifier

X = df[['humidity', 'temperature']]
y = df['weather_encoded']

model = DecisionTreeClassifier(random_state=0)
model.fit(X, y)

pred = model.predict(X)
accuracy_score(y, pred)

"""**Discussion:**
- Why is this a classification problem?
- What is the performance measure used?

## Part 3: Regression vs Classification
"""

# Example regression target (damages in million USD)
damages = [2.5, 1.2, 3.8, 0.5, 4.1]

damages

"""**Task:**
- Predict win/lose → Classification
- Predict damages amount → Regression

Explain why.

## Part 4: Unsupervised Learning – Patient Clustering
"""

from sklearn.cluster import KMeans

patient_data = np.array([
    [80, 2], [85, 3], [60, 1],
    [30, 5], [25, 4], [40, 6]
])

kmeans = KMeans(n_clusters=2, random_state=0)
clusters = kmeans.fit_predict(patient_data)

plt.scatter(patient_data[:,0], patient_data[:,1], c=clusters)
plt.xlabel('Effectiveness')
plt.ylabel('Side Effects')
plt.title('Patient Response Clusters')
plt.show()

"""**Discussion:**
- Why is this unsupervised learning?
- How can this help medical decision making?

## Part 5: Reflection

Answer the following:
1. Which definition of Machine Learning is the most accurate?
2. Why does clustering not require labels?
3. Give one real-world example of:
   - Classification
   - Regression
   - Unsupervised learning
"""